apiVersion: v1
kind: Service
metadata:
  name: nomad
spec:
  selector:
    name: nomad-agent
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 4646
      targetPort: 4646
    - name: rpc
      protocol: TCP
      port: 4647
      targetPort: 4647
