version: '2'

services:
  redis:
    extends: { file: ../docker/common.yml, service: redis }
    ports:
      - "6379:6379"

  docs:
    build:
      context: ../
      dockerfile: docker/docs/Dockerfile
    command: ["npm", "run", "dev-generate-docs"]
    volumes:
      - "../:/usr/src/app"

  nginx:
    extends: { file: ../docker/common.yml, service: nginx }
    ports:
      - "80:80"
    volumes:
      - "../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
      - docs
