version: '2.1'

services:
  docs:
    build:
      context: ../
      dockerfile: docker/docs/Dockerfile
    command: ["npm", "run", "dev-generate-docs"]
    volumes:
      - "../:/usr/src/app"

  nginx:
    build: nginx
    volumes:
      - "../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
      - docs
    labels:
      - SERVICE_IGNORE=true
      - traefik.enabled=true
      - traefik.port=80
      - traefik.frontend.rule=Host:docs.localhost
      - traefik.weight=10

  traefik:
    extends: { file: ../docker/common.yml, service: traefik }
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "../docker/traefik/traefik.toml:/etc/traefik/traefik.toml"

  rabbitmq:
    extends: { file: ../docker/common.yml, service: rabbitmq }
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    extends: { file: ../docker/common.yml, service: mongodb }
    environment:
      - AUTH=no
    ports:
      - "27017:27017"
